#!/usr/bin/python
# LADITools - Linux Audio Desktop Integration Tools
# laditray - System tray integration for LADI
# Copyright (C) 2012 Alessio Treglia <quadrispro@ubuntu.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import os
import sys
import signal
import gettext
import argparse

sig_handler = signal.getsignal(signal.SIGTERM)
signal.signal(signal.SIGINT, sig_handler)

from laditools import _gettext_domain
gettext.install(_gettext_domain)

from laditools import get_version_string
from laditools import LadiConfiguration

from gi.repository import Gtk
from gi.repository import GdkPixbuf
from gi.repository import GObject
from laditools.gtk import LadiManager
from laditools.gtk import find_data_file

timeout_add = GObject.timeout_add

class LadiPlayer(LadiManager):

    # Default configuration
    _default_config = {
        'autostart' : False,
    }

    def on_quit(self, *args, **kwargs):
        Gtk.main_quit()

    def _run_select_studio_dialog(self, title, *args):
        studio_list = self.get_ladish_controller().studio_list()
        if not studio_list:
            dlg = Gtk.MessageDialog(None,Gtk.DialogFlags.MODAL | Gtk.DialogFlags.DESTROY_WITH_PARENT,
                                        Gtk.MessageType.INFO,
                                        Gtk.ButtonsType.CLOSE,
                                        _('No studio is available.'))
            dlg.set_title(title)
            dlg.run()
            dlg.destroy()
            return None
        #dlg = self.builder.get_object('dialog_select_studio')
        dlg = Gtk.Dialog()
        treeview = Gtk.TreeView()

        dlg.set_title(title)
        dlg.get_content_area().pack_start(child=treeview,
                                         expand=True,
                                         fill=True,
                                         padding=10)
        model = Gtk.ListStore(GObject.TYPE_STRING)
        renderer = Gtk.CellRendererText()
        column = Gtk.TreeViewColumn('Available studios', renderer, text=0)

        dlg.set_title(title)
        dlg.add_button(Gtk.STOCK_OK, Gtk.ResponseType.OK)
        dlg.add_button(Gtk.STOCK_CANCEL, Gtk.ResponseType.CANCEL)
        treeview.set_model(model)
        treeview.append_column(column)
        treeview.set_cursor(Gtk.TreePath(path=0),
                                    focus_column=column,
                                    start_editing=False)
        for studio in studio_list:
            model.append((studio,))

        dlg.show_all()
        response = dlg.run()
        ret = None
        if response == Gtk.ResponseType.OK:
            path, column = treeview.get_cursor()
            ret = model[path][0]
        dlg.hide()
        return ret

    def _set_toolbuttons_active(self, **kwargs):
        buttons = self.status_buttons
        if 'all' in kwargs:
            status = kwargs['all']
            for button in buttons:
                buttons[button].set_sensitive(status)
        else:
            for button in kwargs:
                buttons[button].set_sensitive(kwargs[button])

    def update_status_buttons(self, button=None):
        buttons = self.status_buttons
        if self.ladish_is_available():
            # Buttons "rename" and "unload"
            if self.studio_is_loaded():
                self._set_toolbuttons_active(unload=True, rename=True)
                # Buttons "start" and "stop"
                if self.studio_is_started():
                    self._set_toolbuttons_active(start=False, stop=True, save=True)
                else:
                    self._set_toolbuttons_active(start=True, stop=False, save=False)
                    buttons['start'].set_tooltip(_('Start the loaded studio'))
            else:
                self._set_toolbuttons_active(start=True,
                                             stop=False,
                                             save=False,
                                             unload=False,
                                             rename=False)
                buttons['start'].set_tooltip(_('Start automatic studio'))
        else:
            self._set_buttons_active(all=False)

    def update(self, *args):
        try:
            self.update_status_buttons()
        except Exception, err:
            print "Ouch!"
            raise err
        return True

    def action_studio_new(self, action, *args):
        self.studio_new()

    def action_studio_start(self, action, *args):
        if self.studio_is_loaded():
            if not self.studio_is_started():
                self.studio_start()
                self.update_status_buttons()
        else:
            self.jack_start()
            self.update_status_buttons()

    def action_studio_save(self, action, *args):
        self.studio_save()

    def action_studio_stop(self, action, *args):
        if self.studio_is_started():
            self.studio_stop()
            self.update_status_buttons()

    def action_studio_rename(self, action, *args):
        self.studio_rename()
        self.update_status_buttons()

    def action_studio_load(self, action, *args):
        selection = self._run_select_studio_dialog(_('Load studio'))
        if selection:
            self.studio_load(None, None, selection)
        return selection

    def action_studio_delete(self, action, *args):
        selection = self._run_select_studio_dialog(_('Delete studio'))
        if selection:
            self.studio_delete(None, None, selection)
        return selection

    def action_studio_unload(self, action, *args):
        if self.studio_is_loaded():
            self.studio_unload()
            self.update_status_buttons()

    def action_studio_reactivate_ladishd(self, action, *args):
        self.ladish_reactivate()

    def _menu_studio_fill_list(self, widget, *args):
        try:
            menu = widget.get_menu()
        except AttributeError:
            menu = widget.get_submenu()
        try:
            for studio in self.get_ladish_controller().studio_list():
                item = Gtk.MenuItem(studio)
                item.show()
                menu.append(item)
                item.connect("button-release-event", function, studio) # "activate" is not used because of focus bug in pygtk
        except Exception, e:
            self.menu_clear(menu)
            item = Gtk.MenuItem(_("Error obtaining studio list"))
            item.set_sensitive(False)
            item.show()
            menu.append(item)
        if not menu.get_children():
            item = Gtk.MenuItem(_("Empty studio list"))
            item.set_sensitive(False)
            item.show()
            menu.append(item)

    def __init__(self):
        # Handle the configuration
        self.global_config = LadiConfiguration(laditray = self._default_config)
        self.ladiplayer_param_dict = self.global_config.get_config_section ('ladiplayer')
        #autostart = bool(eval(self.ladiplayer_param_dict['autostart']))
        # Build the UI
        LadiManager.__init__(self, self.global_config.get_config_section ('ladiplayer'), False)
        # Build the UI
        self.builder = builder = Gtk.Builder()
        ui_path = find_data_file("ladiplayer.ui")
        builder.add_from_file(ui_path)
        sys.stderr.write( _("Loading interface from %s\n") % ui_path)
        sys.stderr.flush()
        # Retrieve objects
        self.ui = ui = builder.get_object("main_window")
        # Setup status buttons
        actiongroup_studio = builder.get_object("actiongroup_studio")
        self.status_buttons = status_buttons = {}
        for action in actiongroup_studio.list_actions():
            status_buttons[action.get_name()] = action
        # Get the initial status
        self.update ()
        # Add the auto update callback
        self.auto_updater = timeout_add (250, self.update, None)
            
        builder.connect_signals(self)

    def run(self):
        self.ui.show_all()

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=_('graphical front-end that allows users to start, stop and'
                                                    'monitor JACK, as well as start some JACK related applications'),
                                     epilog=_('This program is part of the LADITools suite.'))
    parser.add_argument('--version', action='version', version="%(prog)s " + get_version_string())

    parser.parse_args()
    GObject.threads_init()

    LadiPlayer().run()
    Gtk.main()
    sys.exit(0)
