#!/bin/bash

## ./retrieve_changelog -r tag:0.7.1.. > ChangeLog
python setup.py sdist --formats=gztar,bztar
tarballs=`ls dist`
for tarball in ${tarballs}; do
    gpg --armor --sign --detach-sig dist/${tarball} ;
done
