#!/bin/bash

oldpwd="`pwd`"

cd po
intltool-update --gettext-package laditools --pot
for i in `ls *.po`
do
   intltool-update --gettext-package laditools --dist `echo $i | sed -e 's/.po//'`
done

cd $oldpwd
