#!/usr/bin/env python

import sys
import os
from wmdocklib import wmoo, pywmhelpers
from jack_controller import jack_controller

class wmjackctl(wmoo.Application):
    def __init__(self):
        self.jack = jack_controller()
        wmoo.Application.__init__(
            self,
            #background = os.path.dirname(sys.argv[0]) + os.sep + "background.xpm",
            margin = 2,
            debug = False)

    def update(self):
        lines = ["JACK"]
        if self.jack.is_started():
            lines.append("started")
            lines.append("%.3f %%" % self.jack.get_load())
            xruns = self.jack.get_xruns()
            if xruns > 999:
                xruns = "lot"
            else:
                xruns = str(xruns)
            lines.append("%s xruns" % xruns)
	    rate = self.jack.get_sample_rate()
	    if rate % 1000 == 0:
                lines.append("%.0f Khz" % (rate / 1000))
	    else:
                lines.append("%.1f Khz" % (rate / 1000))
            lines.append("%.1f ms" % self.jack.get_latency())
        else:
            lines.append("stopped")
            lines.append("         ")
            lines.append("         ")
            lines.append("         ")
            lines.append("         ")
        self.put_lines(lines)

    def put_lines(self, lines):
        x = 1
        y = 1
        for line in lines:
            self.putString(x, y, line)
            y += 9

wmjackctl().run()
