#!/usr/bin/env python

import sys
import os
from wmdocklib import wmoo, pywmhelpers
import dbus

name_base = 'org.jackaudio'
controller_interface_name = name_base + '.JackController'
service_name = name_base + '.service'

class jack_controller:
        def __init__(self):
                 self.bus = dbus.SessionBus()
                 self.controller = self.bus.get_object(service_name, "/DefaultController")
                 self.iface = dbus.Interface(self.controller, controller_interface_name)

        def is_started(self):
                return self.iface.IsStarted()

        def get_load(self):
                return self.iface.GetLoad()

        def get_xruns(self):
                return self.iface.GetXruns()

        def get_sample_rate(self):
                return self.iface.GetSampleRate()

        def get_latency(self):
                return self.iface.GetLatency()

        def start(self):
                self.iface.StartServer()

        def stop(self):
                self.iface.StopServer()

        def kill(self):
                self.iface.Exit()

class wmjackctl(wmoo.Application):
    def __init__(self):
        self.jack = jack_controller()
        wmoo.Application.__init__(
            self,
            #background = os.path.dirname(sys.argv[0]) + os.sep + "background.xpm",
            margin = 2,
            debug = False)

    def update(self):
        lines = ["JACK"]
        if self.jack.is_started():
            lines.append("started")
            lines.append("%.3f %%" % self.jack.get_load())
            xruns = self.jack.get_xruns()
            if xruns > 999:
                xruns = "lot"
            else:
                xruns = str(xruns)
            lines.append("%s xruns" % xruns)
	    rate = self.jack.get_sample_rate()
	    if rate % 1000 == 0:
                lines.append("%.0f Khz" % (rate / 1000))
	    else:
                lines.append("%.1f Khz" % (rate / 1000))
            lines.append("%.1f ms" % self.jack.get_latency())
        else:
            lines.append("stopped")
            lines.append("         ")
            lines.append("         ")
            lines.append("         ")
            lines.append("         ")
        self.put_lines(lines)

    def put_lines(self, lines):
        x = 1
        y = 1
        for line in lines:
            self.putString(x, y, line)
            y += 9

wmjackctl().run()
