.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH LADITOOLS 1 "March 2012" "LADI Tools 1.0" "Linux Audio Desktop Integration"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
laditools \- tools to control and monitor LADI (JACK and ladish) systems
.SH SYNOPSIS
.B g15ladi
.PP
.B ladi-control-center
.PP
.B ladi-player
.PP
.B ladi-system-log
.PP
.B ladi-system-tray
.PP
.B wmladi
.SH DESCRIPTION
\fBLADITools\fP is a collection of tools aiming to achieve the goals of the
LADI project to improve desktop integration and user workflow of GNU/Linux
audio system based on JACK and LASH. The tools take advantage of the
D-Bus interfaces recently added to JACK and LASH to ease the configuration
and use of those two great pieces of software.
.PP
The following tools are included:
.TP
.B g15ladi
A JACK monitor for g15 keyboards.
.TP
.B ladi\-control\-center
Graphical interface to setup JACK's configuration.
.TP
.B ladi\-player
Compact front end to that allows users to start, stop and
monitor a LADI system
.TP
.B ladi\-system\-log
A JACK, LASH and a2jmidid log viewer.
.TP
.B ladi\-system\-tray
System tray icon that allows users to start, stop and monitor JACK,
as well as start some JACK related applications.
.TP
.B wmladi
Window Maker dockapp which uses a menu similar
to ladi\-system\-tray's.
.SH AUTHOR
laditools were written by Marc-Olivier Barre <marco@marcochapeau.org>,
Nedko Arnaudov <nedko@arnaudov.name> and
Alessio Treglia <quadrispro@ubuntu.com>.
.PP
This manual page was written by Alessio Treglia <alessio@debian.org>,
for the Debian project (but may be used by others).
